import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Footer from "./_components/Footer/Footer";
import Navbar from "./_components/Navbar/Navbar";
import { Toaster } from "sonner";
import AuthProvider from "./context/authProvider";
import { WishlistProvider } from "./context/wishListContext";
import { ProfileContextProvider } from "./context/ProfileContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider>
              <ProfileContextProvider>

                  <WishlistProvider>

          <Navbar/>
                <Toaster richColors position="top-center" />

        {children}
        <Footer/>
                          </WishlistProvider>
              </ProfileContextProvider>

        </AuthProvider>
        

      </body>
    </html>
  );
}
